module.exports = {
	lights_off: "Вкл. подсветку",
	lights_on: "Выкл. подсветку",
	validate_name: "Пожалуйста введите имя",
	validate_username: "Пожалуйства введите ваш ник",
	validate_pass: "Пожалуйста введите пароль",
	validate_captcha: "Пожалуйста введите код подтверждения",
	validate_email: "Пожалуйста введите ваш настоящий email",
	validate_agree: "Пожалуйста согласитесь с нашими правилами",
	validate_name_long: "Ваше имя должно содержать как минимум 2 символа",
	validate_username_long: "Ваш ник должен содержать как минимум 2 символа",
	validate_pass_long: "Ваш пароль должен содержать как минимум 5 символов",
	validate_confirm_pass_long: "Пожалуйства повторите пароль",
	choose_category: "Выберите категорию",
 	validate_select_file: "Не были выбраны файлы для загрузки.",
 	validate_video_title: "Пожалуйста напишите название видео",
	please_wait: "Загрузка...",
	// upload video page
	swfupload_status_uploaded: "Uploaded",
	swfupload_status_pending: "Continue with the rest of the form.",
	swfupload_status_queued: "Queued",
	swfupload_status_uploading: "Uploading...",
	swfupload_file: "File",
	swfupload_btn_select: "Select",
	swfupload_btn_cancel: "Cancel",
	swfupload_status_error: "Error",
	swfupload_error_oversize: "Size of the selected file(s) is greater than allowed limit",
	swfupload_friendly_maxsize: "",
	// playlist
	playlist_delete_confirm: "Are you sure you want to permanently delete this playlist?\n\nClick 'Cancel' to stop, 'OK' to delete.",
	playlist_delete_item_confirm: "You are about to remove this video from your playlist.\n\nClick 'Cancel' to stop, 'OK' to delete.",
	show_more: "Показать больше",
	show_less: "Show less",
	delete_video_confirmation: "Are you sure you want to delete this video?",
	browse_all: "Browse All"
 }